socket: 'tcp://127.0.0.1:8282'
timeout: 2000
actions:
    mouse1Down:
        type: 'mouse'
        action: 'down'
        target: 'left'
        feedback:
            audio: 'asset/audio/mousedown.ogg'
    mouse1Up:
        type: 'mouse'
        action: 'up'
        target: 'left'
        feedback:
            audio: 'asset/audio/mouseup.ogg'
    mouse2Click:
        type: 'mouse'
        action: 'click'
        target: 'right'
        feedback:
            audio: 'asset/audio/mallet.ogg'
    mouseMove:
        type: 'mouse'
        action: 'move'
    toggleFreeze:
        type: 'mouse'
        action: 'toggleFreeze'
        feedback:
            audio: 'asset/audio/mallet.ogg'
signs:
    pinchIndex:
        pinch:
            pincher: 'indexFinger'
            min: 0.5
    pinchRing:
        pinch:
            pincher: 'ringFinger'
            min: 0.5
    freeHand:
        grab:
            max: 0.4
recipes:
    mouseMove:
        action: 'mouseMove'
        signs:
         - 'freeHand'
        continuous: true
    mouseButton1:
        signs:
         - 'pinchIndex'
        action: 'mouse1Down'
        tearDown: 'mouse1Up'
    mouseButton2:
        signs:
         - 'pinchRing'
        action: 'mouse2Click'
